- lib/backends/webgl/webgl-context-factory.ts
- package-lock.json
- package.json
Currently webgl2 is not working on some environment (for example, macOS).
While the investigating and fix is ongoing, we have this workaround to fallback to webgl1 for non-windows environment.
> webgl: disable webgl2 on non-windows environment

- lib/graph.ts
This change fixes a bug in graph resolving when there is a 'Constant' operator. This shows in issue #16 ( the first model). @hariharans29 @liuziyue 
===
The problem is, we used same node index for `node` and `nodeProto`, https://github.com/Microsoft/onnxjs/blob/6aa8898b619a3ab888151d96f7489db03ae97a9c/lib/graph.ts#L284-L285
but if there is a 'Constant' node, the index will not match:
https://github.com/Microsoft/onnxjs/blob/6aa8898b619a3ab888151d96f7489db03ae97a9c/lib/graph.ts#L242-L262
> graph: fix resolve operator 'Constant'

- lib/api/index.ts
- lib/api/inference-session.ts
- lib/api/onnx-impl.ts
- lib/api/onnx.ts
- lib/api/tensor-impl-utils.ts
- lib/api/tensor.ts
- lib/backend.ts
- lib/backends/backend-cpu.ts
- lib/backends/backend-wasm.ts
- lib/backends/backend-webgl.ts
- lib/backends/index.ts
- test/unittests/api/inference-session.ts
- test/unittests/api/onnx.ts
- test/unittests/api/tensor.ts
- test/unittests/api/types.ts
- test/unittests/index.ts
This change revise the API export:
- make the root exported object is the same object to `global.onnx`
- make no value exported from interface files
- move the definition of `global.onnx` to index.ts
- merge declaration only in index.ts
- add missing jsdoc for some interface member
- add more unit test case in test group `#UnitTest# - API - Check Globals and Imports`
- move `backend` from interface `Environment` to `Onnx`
> api: revise API export

- docs/operators.md
- test/README.md
* operator support table is updated to reflect the fact that we support Constant, Dropout, and Identity for all backends (as they are pre-processed out in the graph). This should save the users confusion as to whether they can use they can use their model even though the operator support table doesn't 'Dropout' op for the 'wasm' backend
* ./test/README.md is out of date. Updated to reflect recent changes.
> doc: update operator support table and test ReadMe

- lib/tensor.ts
- lib/util.ts
* Add data size safety check to ensure the data returned by the DataProvider is consistent with the Tensor dims
* Moving validateDims() into utilities (/lib/util.ts) to be leveraged by other modules going forward
> tensor: add data size safety check and move validateDims() to utilities

- docs/api.md
- lib/api/env-impl.ts
- lib/api/env.ts
- lib/api/index.ts
- lib/api/onnx-impl.ts
- lib/api/onnx.ts
- lib/env.ts
- test/unittests/api/onnx.ts
This change expose `onnx.ENV` to allow user to set global status and flags, and hook it up to the '/lib/env' implementation, which should be used by onnxjs internal implementation.
> api: add ENV implementation

- lib/session.ts
This change is to fix the WebAssembly backend not being able to run on safari. The issue was caused by passing undefined values to optional parameters when loading model in ArrayBuffer.
> WebAssembly to Run On Safari

- lib/backends/webgl/texture-data-encoder.ts
The new version of typescript has updated the interface of `WebGLRenderingContext` thus a build break is occurred. This change fixes the build break.
> src: fix build break on typescript 3.2.2

- karma.conf.js
Sometimes when `npm test` Karma's local web server will cache the contents of a *.onnx* file as a UTF-8 encoded string, causing the test failure. This change fixes this issue.
> test: add flag 'no-cache' for test files in karma

- lib/opset.ts
If there are multiple rules of one operator, the resolve will fail.
example:
```ts
...
['Slice', '', '10+', () => new WebGLSliceV10()],
['Slice', '', '1-9', () => new WebGLSlice()],
...
```
This will fail with error message:
`cannot resolve operator 'Slice' with opsets: ai.onnx v9`
> lib: fix a bug in operator resolve

- test/test-main.ts
- test/test-runner.ts
- contexts should be released only when it is created correctly.
- not allow multiple contexts being created at the same time. this may happen if callers make mistakes, as it is an async function.
> test: fix test context create and release

- README.md
- examples/node/add/index.js
- package-lock.json
- package.json
- test/test-runner.ts
- tools/test-runner-cli-args.ts
- tools/test-runner-cli.ts
- Add dev dependency `onnxjs-node`, an ONNXRuntime Node.js binding
- Update documents and example
- Update test runner to allow backend `onnxruntime` (only works in Node.js)
> backend: add support for ONNXRuntime node.js binding

- test/test-main.ts
- test/test-runner.ts
- test/test-shared.ts
- test/test-types.ts
- tools/test-runner-cli.ts
This change introduce a memory file cache for node tests.
There are several hundreds of node test cases in suite test. The current test runner behavior is to use `fetch()` to request every `.onnx` `.pb` files (for models and inputs/outputs). This means a lot of HTTP requests, and it makes trouble when running tests in BrowserStack, which usually ends up with a timeout failure.
This change introduce a filePath-to-fileContent in-memory map as a file cache. The file content is preloaded and cooked into `testdata.js`, which reduces the request number significantly.
> test: add file cache for node tests

- lib/api/tensor-impl.ts
remove the usage of keyword `arguments`. this helps to avoid the potential failure in later typescript/ES version.
> misc: remove usage of keyword arguments

- test/test-main.ts
- test/test-types.ts
- tools/test-runner-cli.ts
this change allows to specify a platform based condition in test whitelist. for example:
```
...
"test_a",
"test_b",
"test_c",
...
```
===>
```
...
"test_a",
{ "name": "test_b", "condition": "iOS" }, // only run test_b on iOS environment
"test_b",
...
```
> test: allow to specify condition for each test

- lib/graph.ts
- lib/session.ts
- allows implicit inputs in initializers
- allows inputs with multiple None dimensions
Fixes #147
> graph: bugfix for initializer

- .vscode/launch.json
this fixes the project test target "Launch Mocha Tests (node)" in vscode.
> misc: fix vscode debug launch args for node mocha test

- lib/api/onnx.ts
- lib/backends/backend-webgl.ts
- lib/backends/webgl/inference-handler.ts
- lib/backends/webgl/ops/conv.ts
- lib/backends/webgl/ops/softmax.ts
- lib/backends/webgl/ops/split.ts
- lib/backends/webgl/ops/uint8-encode.ts
- lib/backends/webgl/program-manager.ts
- lib/backends/webgl/session-handler.ts
- lib/backends/webgl/texture-manager.ts
- lib/backends/webgl/types.ts
- lib/backends/webgl/webgl-context.ts
- tools/test-runner-cli-args.ts
- tools/test-runner-cli.ts
Introduce a full texture cache that does not only apply to initializers but also the intermedia output of the graph.
NOTE: this PR is based on #158 so please ignore the first commit when reviewing
> webgl: full texture cache

- lib/backend.ts
- lib/backends/cpu/session-handler.ts
- lib/backends/wasm/session-handler.ts
- lib/backends/webgl/session-handler.ts
- lib/operators.ts
- lib/session.ts
- test/test-runner.ts
- test/test-shared.ts
- test/unittests/backends/webgl/test_conv_new.ts
By accessing the graph ( already resolved and finalized ) in operator's initialization, it is possible to access the tensor value of the operator's input, if it's the graph's initializer or const value. This will enable implementation of upcoming operators that want to deal with constant inputs.
> src: allow operators to access graph in initialization

- lib/backends/webgl/ops/gather.ts
- test/data/ops/gather.jsonc
This change fixes 'Gather' with 0 rank indices.
> webgl: fix 'Gather' with 0-rank indices

- lib/backends/webgl/ops/reshape.ts
use a different tensor ID for reshape implementation, when creating a shared texture data.
> webgl: fix tensor data ID in 'Reshape'
